name: otus_hw_main

services:
  main-app:
    container_name: main-service
    build:
      # from project root
      context: ../../
      dockerfile: ./main-service/docker/Dockerfile
    image: main-service-app:0.7.1
    environment: &AUTH
      POSTGRES_SERVER: postgres-db
      POSTGRES_DB: bd_social
      POSTGRES_DB_SCHEMA: bd_social
      POSTGRES_USER: bd_admin
      POSTGRES_PASSWORD: bd_pass
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - social-network
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      rabbit-mq:
        condition: service_started
  postgres-db:
    container_name: postgres-db
    image: postgres:15-alpine
    environment: *AUTH
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - social-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 3s
      timeout: 3s
      retries: 3
  redis-cache:
    container_name: redis-cache
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - social-network
    restart: unless-stopped
  rabbit-mq:
    container_name: rabbit-mq
    image: rabbitmq:4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/
    networks:
      - social-network
    restart: unless-stopped

networks:
  social-network:
    driver: bridge

volumes:
  redis-data:
  rabbitmq_data:
