services:
  influxdb:
    image: influxdb:1.11-alpine
    ports:
      - "8086:8086"
    networks:
      - grafana-influxdb-network
    volumes:
      - ./other/jmeter/influxdb/influx_init.iql:/docker-entrypoint-initdb.d/influx_init.iql

  grafana:
    image: grafana/grafana:12.1
    depends_on:
      - influxdb
    volumes:
      - ./other/jmeter/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    env_file:
      - ./grafana/grafana.env
    links:
      - influxdb
    networks:
      - grafana-influxdb-network

networks:
  grafana-influxdb-network:
    driver: bridge