name: citus_hw

services:
  social-app:
    container_name: "${COMPOSE_PROJECT_NAME}_social_app"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: some-social-app:0.0.5
    environment: &AUTH
      POSTGRES_SERVER: master
      POSTGRES_DB: bd_social
      POSTGRES_DB_SCHEMA: public
      POSTGRES_USER: bd_admin
      POSTGRES_PASSWORD: bd_pass
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - social-network-citus
    depends_on:
      manager:
        condition: service_healthy
  master:
    container_name: "${COMPOSE_PROJECT_NAME}_citus_coordinator"
    image: "citusdata/citus:12.1.3"
    ports: ["${COORDINATOR_EXTERNAL_PORT:-5432}:5432"]
    labels: ["com.citusdata.role=Master"]
    environment:
      <<: *AUTH
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
    networks:
      - social-network-citus
  worker:
    image: "citusdata/citus:12.1.3"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    environment:
      <<: *AUTH
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
    networks:
      - social-network-citus
  manager:
    container_name: "${COMPOSE_PROJECT_NAME}_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [master]
    environment:
      <<: *AUTH
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
    networks:
      - social-network-citus
  redis-cache:
    container_name: "${COMPOSE_PROJECT_NAME}_redis_cache"
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - social-network-citus
    restart: unless-stopped
  rabbit-mq:
    container_name: "${COMPOSE_PROJECT_NAME}_rabbit_mq"
    image: rabbitmq:4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/
    networks:
      - social-network-citus
    restart: unless-stopped

networks:
  social-network-citus:
    driver: bridge

volumes:
  redis-data:
  rabbitmq_data:
  healthcheck-volume: