services:
  social-app:
    container_name: social-app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - social-network
    depends_on:
      postgres-db:
        condition: service_healthy
  postgres-db:
    container_name: postgres-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: bd_social
      POSTGRES_USER: bd_admin
      POSTGRES_PASSWORD: bd_pass
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - social-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 3s
      timeout: 3s
      retries: 3

networks:
  social-network:
    driver: bridge
